version: "2"

services:
  app:
    build: .
    env_file: .env
    volumes:
      - D:/home/projects/python/src/github.com/zenathark/tsbasics:/d/home/projects/python/src/github.com/zenathark/tsbasics
    ports:
      - "2222:22"
      - "8888:8888"
      - "6006:6006"
